apply plugin: 'java'
apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply plugin: 'com.github.gmazzo.buildconfig'
apply plugin: MyCustomPlugin

group = 'com.github.laiis'
version = '0.2.0'

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact("build/libs/ezretrofit-${project.version}-pg.jar")
        }
    }
}

tasks.withType(PublishToMavenLocal) {
    dependsOn 'useproguard'
}
tasks.withType(PublishToMavenRepository) {
    dependsOn 'useproguard'
}

buildConfig {
    useJavaOutput()
    packageName("tw.idv.laiis.ezretrofit")
    buildConfigField("boolean", "DEBUG", "false") // This is set to true for now; in a full Android build it's configured based on debug/release variants.
}

compileJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}

jar {
    archiveVersion = project.version
    archiveBaseName = 'ezretrofit'
}


repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'

    api 'com.squareup.retrofit2:retrofit:2.12.0'
    api 'com.squareup.retrofit2:converter-gson:2.12.0'
    api 'com.squareup.retrofit2:adapter-rxjava2:2.12.0'

    api 'com.squareup.okhttp3:okhttp:4.12.0'
    api 'com.squareup.okhttp3:okhttp-urlconnection:4.12.0'
    api 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    api 'com.squareup.okio:okio:3.4.0'
}

test {
    useJUnitPlatform()
}

buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.guardsquare:proguard-gradle:7.5.0'
        classpath 'com.github.gmazzo.buildconfig:com.github.gmazzo.buildconfig.gradle.plugin:5.3.5'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.named('jar') {
    finalizedBy 'useproguard'
}

tasks.named('useproguard') {
    dependsOn 'jar'
    doLast {
        def version = project.tasks.jar.archiveVersion.get()
        def baseName = project.tasks.jar.archiveBaseName.get()
        file("build/libs/${baseName}-${version}.jar").delete()
        file("build/libs/${baseName}-${version}-proguard.jar").renameTo("build/libs/${baseName}-${version}-pg.jar")
    }
}

class MyCustomPlugin implements Plugin<Project> {

    void apply(Project project) {
        project.tasks.create("useproguard", proguard.gradle.ProGuardTask) {
            configuration 'proguard-rules.pro'
        }

        project.afterEvaluate {
            project.tasks.named("useproguard", proguard.gradle.ProGuardTask) {
                def jarTask = project.tasks.jar
                def version = jarTask.archiveVersion.get()
                def baseName = jarTask.archiveBaseName.get()

                injars "build/libs/${baseName}-${version}.jar"
                outjars "build/libs/${baseName}-${version}-proguard.jar"
            }
        }
    }

}