apply plugin: 'java'
apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply plugin: 'com.github.gmazzo.buildconfig'
apply plugin: MyCustomPlugin

buildConfig {
    useJavaOutput()
    packageName("tw.idv.laiis.ezretrofit")
    buildConfigField("boolean", "DEBUG", "true") // This is set to true for now; in a full Android build it's configured based on debug/release variants.
}

compileJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}

jar {
    archiveVersion = "0.1.2"
    archiveBaseName = 'EZRetrofit'
}


repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'

    api 'com.squareup.retrofit2:retrofit:2.7.2'
    api 'com.squareup.retrofit2:converter-gson:2.7.2'
    api 'com.squareup.retrofit2:adapter-rxjava2:2.7.2'

    api 'com.squareup.okhttp3:okhttp:3.14.7'
    api 'com.squareup.okhttp3:okhttp-urlconnection:3.14.7'
    api 'com.squareup.okhttp3:logging-interceptor:3.14.7'
    api 'com.squareup.okio:okio:2.4.3'
}

buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.guardsquare:proguard-gradle:7.5.0'
        classpath 'com.github.gmazzo.buildconfig:com.github.gmazzo.buildconfig.gradle.plugin:5.3.5'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.named('jar') {
    finalizedBy 'useproguard'
}

tasks.named('useproguard') {
    doLast {
        file('build/libs/EZRetrofit-0.1.2.jar').delete()
        file('build/libs/EZRetrofit-0.1.2-proguard.jar').renameTo('build/libs/EZRetrofit-0.1.2.jar')
    }
}

class MyCustomPlugin implements Plugin<Project> {

    void apply(Project project) {
        project.tasks.create("useproguard", proguard.gradle.ProGuardTask) {
            configuration 'proguard-rules.pro'

            injars "build/libs/EZRetrofit-0.1.2.jar"
            outjars "build/libs/EZRetrofit-0.1.2-proguard.jar"
        }
    }

}